AWSTemplateFormatVersion: 2010-09-09

Description: IAM Role from GitHub with OpenID Connect.

Parameters:
  Thumbprint:
    Type: String
  GitHubRepositoryOwner:
    Type: String

Resources:

  OIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties: 
      ClientIdList: 
        - sts.amazonaws.com
      ThumbprintList: 
        - !Ref Thumbprint
      Url: https://token.actions.githubusercontent.com


  Role:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated:
                - !Ref OIDCProvider
            Action:
              - sts:AssumeRoleWithWebIdentity
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub:
                  - !Sub repo:${GitHubRepositoryOwner}/*
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
      Policies:
        - PolicyName: PutObject-to-CDK-StagingBucket
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                Resource: '!Sub arn:aws:s3:::cdk-*-assets-${AWS::AccountId}-${AWS::Region}'
        - PolicyName: PutObject-to-CDK-StagingBucket
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:CreateChangeSet
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:DeleteChangeSet
                Resource: '*'
