AWSTemplateFormatVersion: 2010-09-09

Description: IAM Role from GitHub with OpenID Connect.

Parameters:
  Thumbprint:
    Type: String
    Default: 6938fd4d98bab03faadb97b34396831e3780aea1
  GitHubRepositoryOwner:
    Type: String

Resources:

  OIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties: 
      ClientIdList: 
        - sts.amazonaws.com
      ThumbprintList: 
        - !Ref Thumbprint
      Url: https://token.actions.githubusercontent.com


  Role:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated:
                - !Ref OIDCProvider
            Action:
              - sts:AssumeRoleWithWebIdentity
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub:
                  - !Sub repo:${GitHubRepositoryOwner}/*
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
      Policies:
        - PolicyName: cdk-assets
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                Resource: '!Sub arn:aws:s3:::cdk-*-assets-*'
        - PolicyName: cdk-container-assets
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ecr:BatchCheckLayerAvailability
                  - ecr:PutImage
                  - ecr:InitiateLayerUploa
                  - ecr:UploadLayerPar
                  - ecr:CompleteLayerUpload
                Resource: '!Sub arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/cdk-*-container-assets-*'
        - PolicyName: GetAuthorizationToken
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: ecr:GetAuthorizationToken
                Resource: '*'
        - PolicyName: ChangeSetOperations
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:CreateChangeSet
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:DeleteChangeSet
                Resource: '*'
