AWSTemplateFormatVersion: 2010-09-09

Description: cdk deploy from github actions

Parameters:
  GitHubOrg:
    Description: Organization name or account name
    Type: String
  GitHubRepo:
    Description: Repository name
    Type: String
    Default: '*'
  GitHubBranch:
    Type: String
    Default: '*'

Resources:
  role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub 'arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com'
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${GitHubOrg}/${GitHubRepo}:ref:refs/heads/${GitHubBranch}
      Policies:
        - PolicyName: cdk-deploy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: sts:AssumeRole
                Resource:
                  - !Sub 'arn:aws:iam::${AWS::AccountId}:role/cdk-*-deploy-role-${AWS::AccountId}-*'
                  - !Sub 'arn:aws:iam::${AWS::AccountId}:role/cdk-*-lookup-role-${AWS::AccountId}-*'
              - Effect: Allow
                Action: iam:PassRole
                Resource: !Sub 'arn:aws:iam::${AWS::AccountId}:role/cdk-*-cfn-exec-role-${AWS::AccountId}-*'
        - PolicyName: cdk-assets
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: sts:AssumeRole
                Resource:
                  - !Sub 'arn:aws:iam::${AWS::AccountId}:role/cdk-*-file-publishing-role-${AWS::AccountId}-*'
                  - !Sub 'arn:aws:iam::${AWS::AccountId}:role/cdk-*-image-publishing-role-${AWS::AccountId}-*'
