AWSTemplateFormatVersion: 2010-09-09

Description: Publish image from GitHub Actions.

Parameters:
  GitHubOrg:
    Description: Organization name or account name
    Type: String
  GitHubRepo:
    Description: Repository name
    Type: String
    Default: '*'
  GitHubRef:
    Type: String
    Default: 'refs/heads/main'
  EcrRepoName:
    Description: ECR Repository Name
    Type: String
    Default: '*'

Resources:
  role:
    Type: AWS::IAM::Role
    Properties:
      Description: Role for GitHub Actions to publish image to ECR Public
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub 'arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com'
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${GitHubOrg}/${GitHubRepo}:ref:${GitHubRef}
      Policies:
        - PolicyName: ecr-login
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                Resource:
                  - '*'
        - PolicyName: ecr-push
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ecr:BatchCheckLayerAvailability
                  - ecr:BatchGetImage
                  - ecr:PutImage
                  - ecr:InitiateLayerUpload
                  - ecr:UploadLayerPart
                  - ecr:CompleteLayerUpload
                Resource: !Sub 'arn:${AWS::Partition}:ecr:${AWS::Region}:${AWS::AccountId}:repository/${EcrRepoName}'
