name: publish
on:
  push:
    branches:
      - main
  workflow_dispatch: {}
env:
  AWS_REGION : us-west-2
  BUCKET_NAME: mats-toolbox

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # needed to interact with GitHub's OIDC Token endpoint.
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Publish
        run: aws s3 sync ./ s3://${{ env.BUCKET_NAME }}/assume-role-with-github-oidc/latest/ --exclude "*" --include "*.yaml" --acl public-read --delete
