name: publish
on:
  push:
    branches:
      - main
  workflow_dispatch: {}
env:
  AWS_REGION : us-west-2

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # needed to interact with GitHub's OIDC Token endpoint.
      contents: read
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish
        run: aws s3 sync --delete --acl public-read --exclude ".git/*" ./ s3://mats-templates/assume-role-with-github-oidc/latest/
